require 'user.plugins'
require 'user.settings'
require 'user.globals'
require 'user.commands'
require 'user.mappings'
require 'user.treesitter'
require 'user.indent'
require 'user.gitsigns'
require 'user.startup'
require 'user.completion'
require 'user.lsp'
require 'user.autopairs'
require 'user.git_conflict'

